Nakamura/develop/readyToCss
jphacks/B_2214 pull request #10
Opened 2022-10-14 16:11 UTC by kosei8

2022-10-14 16:52 UTC, kazuyahirotsu requested changes

2022-10-14 16:52 UTC, kazuyahirotsu commented on oyster/src/components/main/TopPage/elements/CalculateSection/index.js
> +const CaluculateSection = () => {
typo

2022-10-14 16:52 UTC, kazuyahirotsu commented on oyster/src/components/main/TopPage/elements/CalculateSection/index.js
> +import { useTopPageState } from '../../hoooks/useTopPageState';
typo

2022-10-14 16:52 UTC, kazuyahirotsu commented on oyster/src/components/main/TopPage/elements/DrawCanvasSection/index.js
> +import { useTopPageState } from '../../hoooks/useTopPageState';
typo

2022-10-14 16:52 UTC, kazuyahirotsu commented on oyster/src/components/main/TopPage/elements/DropImageSection/index.js
> +import { useTopPageState } from '../../hoooks/useTopPageState';
typo

2022-10-14 17:16 UTC, kazuyahirotsu commented on oyster/src/components/main/TopPage/elements/DropImageSection/index.js
> +            <p>Drag &aposn drop the image here, or click to select the image</p>
typo

2022-10-14 18:07 UTC, merged

2022-10-15 04:35 UTC, kosei8 commented
LGTM
TopPage以外も増えたらまた見直すかも構造